(tool-bar-mode -1)
(scroll-bar-mode -1)
(menu-bar-mode -1)
(fringe-mode 10)
  (when (string-equal (file-name-nondirectory (or load-file-name buffer-file-name)) "early-init.el")
    (message "Loading early-init.el")
    (setq package-enable-at-startup nil)
    (setenv "LSP_USE_PLISTS" "true"))
